import React from "react";
import { ThemeProvider } from "@mui/material/styles";
import theme from "../themes/theme";
import "../styles/globals.css";
import ClientLayout from "./clientLayout";
import { AdminProvider } from "./context/adminContext";
import { CashierProvider } from "./context/cashierContext";

export const metadata = {
  title: "Airupees",
  description: "Generated by create next app",
};

function Layout({ children }) {
  return (
    <ThemeProvider theme={theme}>
      <html lang="en">
        <body>
          <AdminProvider>
            <CashierProvider>
              <ClientLayout>{children}</ClientLayout>
            </CashierProvider>
          </AdminProvider>
        </body>
      </html>
    </ThemeProvider>
  );
}

export default Layout;
